name: geometry.js docs
on:
  repository_dispatch:
    types: [generate-docs]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repository }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: yarn --frozen-lockfile
      - run: yarn docs:generate
      - uses: actions/upload-artifact@master
        with:
          name: geometryjs-docs
          path: docs
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/upload-artifact@master
        with:
          name: geometryjs-docs
          path: docs
